require:
  - rubocop-rails

AllCops:
  NewCops: disable

Style/Documentation:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Rails/UniqueValidationWithoutIndex:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: false

Metrics/MethodLength:
  Max: 15

Style/IfUnlessModifier:
  Enabled: false

Style/GuardClause:
  Enabled: false